version: '3.9'

services:
  frontendmandiri:
    container_name: frontendmandiri
    image: frontendmandiri/1.0
    build: ./vueProjectDMCabang
    ports:
      - "8090:8090"
    x-develop:
      watch:
        - action: rebuild
          path: frontendmandiri
          ignore:
            - node_modules/  
  
  java_app_dmd:
    container_name: java_app_dmd
    image: dmd/java_app_dmd:0.0.1
    build: ./java-live-api-dmd
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_app_dmd_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      java_app_dmd_db:
        condition: service_healthy
      
  java_app_dmd_db:
    container_name: java_app_dmd_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5 

volumes:
  pgdata: {}